In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.cluster import KMeans 
from sklearn.preprocessing import StandardScaler
%matplotlib inline

In [2]:
cust_df = pd.read_csv("Cust_Segmentation.csv")
cust_df

Customer Id  Age  Edu  Years Employed  Income  Card Debt  Other Debt  \
0              1   41    2               6      19      0.124       1.073   
1              2   47    1              26     100      4.582       8.218   
2              3   33    2              10      57      6.111       5.802   
3              4   29    2               4      19      0.681       0.516   
4              5   47    1              31     253      9.308       8.908   
..           ...  ...  ...             ...     ...        ...         ...   
845          846   27    1               5      26      0.548       1.220   
846          847   28    2               7      34      0.359       2.021   
847          848   25    4               0      18      2.802       3.210   
848          849   32    1              12      28      0.116       0.696   
849          850   52    1              16      64      1.866       3.638   

     Defaulted Address  DebtIncomeRatio  
0          0.0  NBA001              6.3  
1          0.0  NBA021             12.8  
2          1.0  NBA013             20.9  
3          0.0  NBA009              6.3  
4          0.0  NBA008              7.2  
..         ...     ...              ...  
845        NaN  NBA007              6.8  
846        0.0  NBA002              7.0  
847        1.0  NBA001             33.4  
848        0.0  NBA012              2.9  
849        0.0  NBA025              8.6  

[850 rows x 10 columns]

In [3]:
cust_df.columns.values

array(['Customer Id', 'Age', 'Edu', 'Years Employed', 'Income',
       'Card Debt', 'Other Debt', 'Defaulted', 'Address',
       'DebtIncomeRatio'], dtype=object)

In [4]:
#drop customer id and address
cust_df = cust_df.reindex(columns=['Age', 'Edu', 'Years Employed', 'Income', 'Card Debt', 'Other Debt', 'Defaulted', 'DebtIncomeRatio'])

In [5]:
cust_df

Age  Edu  Years Employed  Income  Card Debt  Other Debt  Defaulted  \
0     41    2               6      19      0.124       1.073        0.0   
1     47    1              26     100      4.582       8.218        0.0   
2     33    2              10      57      6.111       5.802        1.0   
3     29    2               4      19      0.681       0.516        0.0   
4     47    1              31     253      9.308       8.908        0.0   
..   ...  ...             ...     ...        ...         ...        ...   
845   27    1               5      26      0.548       1.220        NaN   
846   28    2               7      34      0.359       2.021        0.0   
847   25    4               0      18      2.802       3.210        1.0   
848   32    1              12      28      0.116       0.696        0.0   
849   52    1              16      64      1.866       3.638        0.0   

     DebtIncomeRatio  
0                6.3  
1               12.8  
2               20.9  
3                6.3  
4                7.2  
..               ...  
845              6.8  
846              7.0  
847             33.4  
848              2.9  
849              8.6  

[850 rows x 8 columns]

In [6]:
#filter NaN
cust_df[cust_df.isna().any(axis=1)]

Age  Edu  Years Employed  Income  Card Debt  Other Debt  Defaulted  \
5     40    1              23      81      0.998       7.831        NaN   
8     26    1               5      18      0.575       2.215        NaN   
11    34    2               9      40      0.374       0.266        NaN   
13    46    1               6      30      1.415       3.865        NaN   
15    24    1               1      16      0.185       1.287        NaN   
..   ...  ...             ...     ...        ...         ...        ...   
818   35    2               0      35      2.383       1.957        NaN   
820   37    1               4      24      0.419       2.989        NaN   
825   32    2              12     116      4.027       2.585        NaN   
835   21    3               0      41      2.367       5.628        NaN   
845   27    1               5      26      0.548       1.220        NaN   

     DebtIncomeRatio  
5               10.9  
8               15.5  
11               1.6  
13              17.6  
15               9.2  
..               ...  
818             12.4  
820             14.2  
825              5.7  
835             19.5  
845              6.8  

[150 rows x 8 columns]

In [8]:
cust_df.fillna(0,inplace=True)
cust_df

Age  Edu  Years Employed  Income  Card Debt  Other Debt  Defaulted  \
0     41    2               6      19      0.124       1.073        0.0   
1     47    1              26     100      4.582       8.218        0.0   
2     33    2              10      57      6.111       5.802        1.0   
3     29    2               4      19      0.681       0.516        0.0   
4     47    1              31     253      9.308       8.908        0.0   
..   ...  ...             ...     ...        ...         ...        ...   
845   27    1               5      26      0.548       1.220        0.0   
846   28    2               7      34      0.359       2.021        0.0   
847   25    4               0      18      2.802       3.210        1.0   
848   32    1              12      28      0.116       0.696        0.0   
849   52    1              16      64      1.866       3.638        0.0   

     DebtIncomeRatio  
0                6.3  
1               12.8  
2               20.9  
3                6.3  
4                7.2  
..               ...  
845              6.8  
846              7.0  
847             33.4  
848              2.9  
849              8.6  

[850 rows x 8 columns]

In [9]:
#check again
cust_df[cust_df.isna().any(axis=1)]

Empty DataFrame
Columns: [Age, Edu, Years Employed, Income, Card Debt, Other Debt, Defaulted, DebtIncomeRatio]
Index: []

In [10]:
#normalize to standard deviations
X = cust_df.values
X

array([[41.   ,  2.   ,  6.   , ...,  1.073,  0.   ,  6.3  ],
       [47.   ,  1.   , 26.   , ...,  8.218,  0.   , 12.8  ],
       [33.   ,  2.   , 10.   , ...,  5.802,  1.   , 20.9  ],
       ...,
       [25.   ,  4.   ,  0.   , ...,  3.21 ,  1.   , 33.4  ],
       [32.   ,  1.   , 12.   , ...,  0.696,  0.   ,  2.9  ],
       [52.   ,  1.   , 16.   , ...,  3.638,  0.   ,  8.6  ]])

In [11]:
X = StandardScaler().fit_transform(X)
X

array([[ 0.74291541,  0.31212243, -0.37878978, ..., -0.59048916,
        -0.52379654, -0.57652509],
       [ 1.48949049, -0.76634938,  2.5737211 , ...,  1.51296181,
        -0.52379654,  0.39138677],
       [-0.25251804,  0.31212243,  0.2117124 , ...,  0.80170393,
         1.90913822,  1.59755385],
       ...,
       [-1.24795149,  2.46906604, -1.26454304, ...,  0.03863257,
         1.90913822,  3.45892281],
       [-0.37694723, -0.76634938,  0.50696349, ..., -0.70147601,
        -0.52379654, -1.08281745],
       [ 2.1116364 , -0.76634938,  1.09746566, ...,  0.16463355,
        -0.52379654, -0.2340332 ]])

In [12]:
clusterNum = 3
k_means = KMeans(init = "k-means++", n_clusters = clusterNum, n_init = 12)
k_means.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=12, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [13]:
k_means.labels_

array([0, 2, 1, 0, 2, 2, 0, 0, 0, 2, 1, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
       1, 2, 2, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 1, 1, 0, 2, 1, 2, 0, 2,
       0, 2, 0, 0, 0, 0, 2, 2, 1, 0, 1, 1, 1, 0, 0, 0, 2, 0, 2, 2, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 2, 0, 2, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 2, 0, 1, 1, 2, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 2, 1, 0,
       0, 0, 0, 2, 1, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 1,
       0, 0, 1, 2, 1, 0, 0, 2, 1, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 2,
       2, 0, 2, 0, 1, 0, 0, 1, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0,
       1, 2, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1, 2, 0, 0, 0,
       0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2, 1, 0, 1, 0, 0, 0, 2, 0, 1,
       2, 1, 0, 2, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 2, 0, 0, 2, 0,
       2, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0, 1, 2, 0,

In [14]:
k3_cust_df = cust_df
k3_cust_df

Age  Edu  Years Employed  Income  Card Debt  Other Debt  Defaulted  \
0     41    2               6      19      0.124       1.073        0.0   
1     47    1              26     100      4.582       8.218        0.0   
2     33    2              10      57      6.111       5.802        1.0   
3     29    2               4      19      0.681       0.516        0.0   
4     47    1              31     253      9.308       8.908        0.0   
..   ...  ...             ...     ...        ...         ...        ...   
845   27    1               5      26      0.548       1.220        0.0   
846   28    2               7      34      0.359       2.021        0.0   
847   25    4               0      18      2.802       3.210        1.0   
848   32    1              12      28      0.116       0.696        0.0   
849   52    1              16      64      1.866       3.638        0.0   

     DebtIncomeRatio  
0                6.3  
1               12.8  
2               20.9  
3                6.3  
4                7.2  
..               ...  
845              6.8  
846              7.0  
847             33.4  
848              2.9  
849              8.6  

[850 rows x 8 columns]

In [15]:
k3_cust_df['Cluster'] = k_means.labels_
k3_cust_df

Age  Edu  Years Employed  Income  Card Debt  Other Debt  Defaulted  \
0     41    2               6      19      0.124       1.073        0.0   
1     47    1              26     100      4.582       8.218        0.0   
2     33    2              10      57      6.111       5.802        1.0   
3     29    2               4      19      0.681       0.516        0.0   
4     47    1              31     253      9.308       8.908        0.0   
..   ...  ...             ...     ...        ...         ...        ...   
845   27    1               5      26      0.548       1.220        0.0   
846   28    2               7      34      0.359       2.021        0.0   
847   25    4               0      18      2.802       3.210        1.0   
848   32    1              12      28      0.116       0.696        0.0   
849   52    1              16      64      1.866       3.638        0.0   

     DebtIncomeRatio  Cluster  
0                6.3        0  
1               12.8        2  
2               20.9        1  
3                6.3        0  
4                7.2        2  
..               ...      ...  
845              6.8        0  
846              7.0        0  
847             33.4        1  
848              2.9        0  
849              8.6        2  

[850 rows x 9 columns]

In [16]:
k3_cust_df.groupby('Cluster').mean()

Age       Edu  Years Employed      Income  Card Debt  \
Cluster                                                               
0        33.817505  1.603352        7.625698   36.143389   0.853128   
1        31.891566  1.861446        3.963855   31.789157   1.576675   
2        43.000000  1.931973       17.197279  101.959184   4.220673   

         Other Debt  Defaulted  DebtIncomeRatio  
Cluster                                          
0          1.816855   0.000000         7.964991  
1          2.843355   0.987952        13.994578  
2          7.954483   0.129252        13.915646

In [17]:
#k = 5
clusterNum = 5
k_means = KMeans(init = "k-means++", n_clusters = clusterNum, n_init = 12)
k_means.fit(X)
k5_cust_df = cust_df
k5_cust_df['Cluster'] = k_means.labels_
k5_cust_df.groupby('Cluster').mean()

Age       Edu  Years Employed      Income  Card Debt  \
Cluster                                                               
0        33.593407  3.483516        5.197802   43.659341   1.122879   
1        32.075419  1.310056        6.055866   29.720670   0.702022   
2        31.886076  1.778481        4.018987   30.962025   1.631367   
3        41.694581  1.463054       16.320197   72.374384   1.989369   
4        43.325000  2.250000       17.300000  136.925000   8.129825   

         Other Debt  Defaulted  DebtIncomeRatio  
Cluster                                          
0          2.459659   0.065934         8.745055  
1          1.538961   0.000000         7.894693  
2          2.787449   0.987342        14.253165  
3          4.323054   0.009852         9.823153  
4         13.104575   0.475000        19.442500

In [18]:
#k = 7
clusterNum = 7
k_means = KMeans(init = "k-means++", n_clusters = clusterNum, n_init = 12)
k_means.fit(X)
k7_cust_df = cust_df
k7_cust_df['Cluster'] = k_means.labels_
k7_cust_df.groupby('Cluster').mean()

Age       Edu  Years Employed      Income  Card Debt  \
Cluster                                                               
0        39.381643  1.256039       11.038647   43.048309   0.980739   
1        44.282609  1.760870       19.358696  101.260870   2.531587   
2        33.632184  3.494253        5.114943   43.563218   1.006161   
3        46.285714  1.928571       22.642857  213.142857  11.737786   
4        31.609929  1.709220        3.709220   28.801418   1.296241   
5        37.342466  2.041096       10.493151   59.589041   4.347014   
6        28.779661  1.317797        4.932203   26.533898   0.645809   

         Other Debt  Defaulted  DebtIncomeRatio  
Cluster                                          
0          2.021976   0.000000         7.446860  
1          5.699337   0.000000         8.983696  
2          2.266793   0.068966         8.111494  
3         16.239857   0.571429        16.821429  
4          2.319986   1.000000        12.992199  
5          7.958466   0.383562        21.819178  
6          1.446669   0.000000         8.101695

In [21]:
#only use age, edu, income
X = cust_df.reindex(columns=["Age","Edu","Income"]).values
X = StandardScaler().fit_transform(X)
clusterNum = 3
k_means = KMeans(init = "k-means++", n_clusters = clusterNum, n_init = 12)
k_means.fit(X)
k3_cust_df2 = cust_df.reindex(columns=["Age","Edu","Income"])
k3_cust_df2['Cluster'] = k_means.labels_
k3_cust_df2.groupby('Cluster').mean()

Age       Edu     Income
Cluster                                
0        36.616438  3.404110  66.061644
1        29.460280  1.378505  29.247664
2        42.826087  1.329710  63.445652